In [25]:
# Render our plots inline
%matplotlib inline
%pylab inline  
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab

# General Plotting Parameters
mpl.rcParams['figure.figsize'] = (8,5)
mpl.rcParams['lines.linewidth'] = 2.5
mpl.rcParams['font.weight'] = 'bold'
mpl.rcParams['axes.linewidth'] = 1.5
mpl.rcParams['font.size'] = 14.
mpl.rcParams['legend.fontsize'] = 12.
mpl.rcParams['axes.labelsize'] = 12.
mpl.rcParams['xtick.labelsize'] = 10.
mpl.rcParams['ytick.labelsize'] = 10.
mpl.rcParams['xtick.minor.pad'] = 4
mpl.rcParams['xtick.direction'] = 'out'
mpl.rcParams['ytick.direction'] = 'out'

#Git says this is patched, but it doesn't work from Pip --upgrade 26-mar-2015
#mpl.rcParams['xtick.minor.visible'] = True  

# These are the "Tableau 20" colors as RGB.  
tableau20 = [(31, 119, 180), (174, 199, 232), (255, 127, 14),
             (255, 187, 120), (44, 160, 44), (152, 223, 138),
              (148, 103, 189),
             (197, 176, 213), (140, 86, 75), (196, 156, 148),  
             (227, 119, 194), (247, 182, 210), (127, 127, 127),
             (199, 199, 199), (188, 189, 34), (219, 219, 141),
             (23, 190, 207), (158, 218, 229),(214, 39, 40), (255, 152, 150)]  
    
# Scale the RGB values to the [0, 1] range,
# which is the format matplotlib accepts.  
for i in range(len(tableau20)): 
    r, g, b = tableau20[i]  
    tableau20[i] = (r / 255., g / 255., b / 255.)  


Populating the interactive namespace from numpy and matplotlib


In [60]:
import hist_bench
reload(hist_bench)
from hist_bench import get_data
from hist_bench import calc_pursuit
from hist_bench import get_prolif_pe

bin_edges = [1,2,3,4,5,6,7,8,9,10]

In [35]:
path = "/Users/mbmcgarry/git/data_analysis/data/v1.3/multi_lat/"
file = "test.tsv"

factor_weights = np.array([0.15, 0.1, 0.16, 0.09, 0.1,0.1, 0.15, 0.15])

countries, col_names, raw_data = get_data(path+file)


In [64]:
all_pe_vals = calc_pursuit(raw_data, factor_weights)
pursue_pes = get_prolif_pe(countries, all_pe_vals)

pursue_hist, edges_p = np.histogram(pursue_pes,bins=bin_edges)
all_hist, edges_a = np.histogram(all_pe_vals, bins=bin_edges)

prolif_pes, pursue_hist

([5.69,
  3.2,
  5.46,
  6.1,
  4.1,
  5.25,
  7.96,
  7.06,
  5.55,
  4.94,
  5.1,
  8.16,
  4.21,
  5.86,
  6.36,
  5.45,
  3.55,
  6.2,
  8.35],
 array([0, 0, 2, 3, 7, 3, 2, 2, 0]))

In [65]:
all_pe_vals,all_hist


([7.05,
  5.69,
  3.2,
  3.69,
  5.46,
  6.1,
  4.1,
  5.25,
  5.31,
  7.96,
  3.6,
  7.06,
  5.55,
  4.94,
  5.51,
  5.1,
  8.16,
  4.21,
  5.86,
  3.41,
  6.36,
  4.51,
  3.09,
  5.45,
  3.55,
  6.2,
  8.35],
 array([0, 0, 6, 4, 9, 3, 3, 2, 0]))

In [70]:
frac_hist=np.nan_to_num(pursue_hist.astype(float)/all_hist.astype(float))
frac_hist

array([ 0.        ,  0.        ,  0.33333333,  0.75      ,  0.77777778,
        1.        ,  0.66666667,  1.        ,  0.        ])

In [72]:
plt.bar(frac_hist, barwidth=1)

TypeError: bar() takes at least 2 arguments (1 given)